### ISSUE TITLE
Error when uses modded block in procedure

### ISSUE THREAD

**Issue by Donne431** [PluginSmiths/Creating-addons-support#5]
At the moment I don't use 4.1 due to its partial instability, so I use 4.0. 
When using a block from mods in the procedure, it gives an error: "incomparable types: Block and RegistryObject".
Screenshot procedure:
![изображение](https://github.com/user-attachments/assets/e23ecf7b-327b-4257-b256-3d6bc01335df) @
(Sorry for Russian Language)
I would like to know if this bug is fixing/fixed (for example in 4.1)?

**Comment by Donne431** [comment]
I found where the error is. 
For some reason, when using a block from a mod, Mcreator doesn't generate the code correctly. 
Instead:
![изображение](https://github.com/user-attachments/assets/90792bd6-de0b-4d77-a04b-9db38a28ab4c)
Does it:
![изображение](https://github.com/user-attachments/assets/e9016a7a-094b-4474-b81a-e8a49c3ca13e)

**Comment by OVNSAME** [comment]
It was already fixed

**Comment by OVNSAME** [comment]
Я русский кстати

**Comment by Donne431** [comment]
Я знаю, но я прост не знал второй разраб плагина русский иль нет, поэтому вот перестраховался, если он бы ответил на тикет.
