### ISSUE TITLE
Mod Request

### ISSUE THREAD

**Issue by Tenchu98** [PluginSmiths/Creating-addons-support#6]
I am not sure if this is where you want requests, or if this mod is even feasible for you to add, but I would like to request support for silent gear. It would be nice to be able to add custom traits, materials, recipes, tool parts, blueprints, and templates to our mcreator mods so as to make them compatible with silent gear.

**Comment by OVNSAME** [comment]
There are can be only bug reports, not mod requests. And I'll not add this mod.
